---
- name: Install oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  args:
    creates: ~/.oh-my-zsh # avoid re-installation if oh-my-zsh already installed
  

- name: Install Plugin autosuggestions
  shell: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

- name: Install Plugin zsh-z 
  shell: "git clone https://github.com/agkozak/zsh-z ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-z"

- name: Install plugin zsh-syntax-highlighting
  shell: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"

- name: copy zshrc file
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: "0600"
